### PR TITLE
Fix makeshift pool

### LINKED ISSUE #52: no export
https://github.com/bartlomieju/deno-postgres/blob/c6a53b5cead678b9955a7e08e4d478e19091f83e/mod.ts#L3

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #52, and partially #49

### CODE REVIEW

File: client.ts [hunk 1]
```diff
@@ -29,29 +26,31 @@ export class Client {
...
+    ...args: any[]
+  ): Promise<QueryResult> {
+    const query = new Query(text, ...args);
+    return await this._connection.query(query);
+  }
 
-  async end(): Promise<void> {
-    this.release();
+  async release(): Promise<void> {
+    await this._releaseCallback();
```
Comment (hayd) [inline client.ts]: Isn't this now unsafe if called twice? (puts the connection back into the pool array twice).

Comment (bartlomieju) [reply client.ts]: Good catch @hayd - since you were working on original implementation would you mind taking a look at #49 ?
